name: Metrics action
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.svg
          user: sbrownbear
          committer_message: "chore: update ${filename}"
          config_timezone: Europe/Paris
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.repositories, base.activity+community, isocalendar, music
          output_condition: skip-if-only-metadata-changed
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: FreeMarker, Sass


      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.plugin.achievements.compact.svg
          user: sbrownbear
          base: ""
          output_action: gist
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, developer, member, deployer, contributor, influencer, 
            stargazer, maintainer, chatter, inspirer, automator, infographile
          plugin_achievements_display: compact
          plugin_achievements_threshold: X


      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.GH_TOKEN }}
          user: sbrownbear
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, developer, deployer, automator



  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2