name: Metrics of languages and Achievements
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.plugin.languages.indepth.svg
          user: sbrownbear
          base: "repositories"
          plugin_languages: yes
          plugin_languages_skipped: lowlighter/metrics
          plugin_languages_colors: 0:#FFD147, 1:#bb99ff, 2:#33ADFF, 3:FFA3FF, 4:85FFFF, 5:FF9966, 6:FFFFA3
          plugin_languages_limit: 7

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.plugin.achievements.compact.svg
          user: sbrownbear
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X



  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2